# Generated by Django 6.0 on 2025-12-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
