# Generated by Django 6.0 on 2025-12-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "emp_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("emp_name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
            ],
        ),
    ]
